const aa_nimet = [
    ["Mikki kiipelissä",""],
    ["Aku Ankka ja Karhukopla",""],
    ["Mikki ja viidakon vaarat",""],
    ["Älä hermoile, Roope-setä",""],
    ["Mikki ja Hessu timanttien jäljillä",""],
    ["Aku Baba ja viisi rosvoa",""],
    ["Mikki Hiiren kuuma kesä",""],
    ["Aku ja Amerikan keisari",""],
    ["Ota rennosti, Aku",""],
    ["Roope näkee punaista",""],
    ["Roope Suuri",""],
    ["Tervetuloa Ankkalinnaan",""],
    ["Ritari Peloton",""],
    ["Perhonen sentään",""],
    ["Varsinainen välkky",""],
    ["Voimakolmikko",""],
    ["Roopen joulutervehdys",""],
    ["Aku urhokas",""],
    ["Roope-sedän miljoonat",""],
    ["Aku, Villin lännen kuningas",""],
    ["Roope-setä voittaa pelin",""],
    ["Aku Ankka pinteessä",""],
    ["Mikki kuulee kummia",""],
    ["Roope-sedän maailmanmatkat",""],
    ["Mikki vauhdissa",""],
    ["Aku ei anna periksi",""],
    ["Mikki on suurin",""],
    ["Rohkea rokan syö",""],
    ["Lännen sankarit",""],
    ["Ympäri mennään, yhteen tullaan",""],
    ["Aku on yliveto",""],
    ["Onnenpoika Aku Ankka",""],
    ["Roopen rahahuolet",""],
    ["Supermikki",""],
    ["Aku Ankan muistelmat",""],
    ["Aku kuumilla jäljillä",""],
    ["Roope ja Kroisos kilpasilla",""],
    ["Varo velhoja, Roope-setä",""],
    ["Heipparallaa, Aku Ankka",""],
    ["Täyttä vauhtia, Mikki Hiiri",""],
    ["Aku Taikaviitta",""],
    ["Mikki johtaa joukkoa",""],
    ["Ruorimies Roope",""],
    ["Täältä tulee Aku",""],
    ["Mikin napakymppi",""],
    ["Roopen kolikkokierre",""],
    ["Rosvojen jäljillä",""],
    ["Taikaviitta taas vauhdissa",""],
    ["Mikki ja Aku",""],
    ["Rahamies Roope",""],
    ["Pää pystyyn, Aku Ankka",""],
    ["Jos kultaa kaivanet",""],
    ["Mikki panee tuulemaan",""],
    ["Selvää sävelet",""],
    ["Mikki kummitusjahdissa",""],
    ["Taikaviitta saa vastustajan",""],
    ["Akun onnenpäivät",""],
    ["Aku pitää pintansa",""],
    ["Mikki menopäällä",""],
    ["Akua aina tarvitaan",""],
    ["Roopen unelmaretket",""],
    ["Puuhapari Mikki ja Minni",""],
    ["Aku maankiertäjä",""],
    ["Mikki Perushiiri",""],
    ["Jäitä hattuun, Aku",""],
    ["Voittamaton Roope-setä",""],
    ["Mikki Hiiri ja Musta Pekka",""],
    ["Roopen kootut rikkaudet",""],
    ["Paljon melua Akusta",""],
    ["Mikki puuttuu peliin",""],
    ["Aku, perheen ylpeys",""],
    ["Taikaviitan tempaukset",""],
    ["Mikin hurjat jutut",""],
    ["Anteeksi, nimeni on Ankka",""],
    ["Akun banaanipotku",""],
    ["Roope-sedän onnenrahat",""],
    ["Mikki historian pyörteissä",""],
    ["Aku parrasvaloissa",""],
    ["Roope-sedän rahasafari",""],
    ["Taikaviitan tanssiinkutsu",""],
    ["Järki käteen, Aku Ankka",""],
    ["Mikki Hiiri junailee",""],
    ["Rahat tai henki!",""],
    ["Mikki taas kuvassa",""],
    ["Aku maailman melskeissä",""],
    ["Minä olen pomo",""],
    ["Mikki esiin!",""],
    ["Aku menestyksen polulla",""],
    ["Aku monessa mukana",""],
    ["Kullan mahti",""],
    ["Mikin kuulento",""],
    ["Roopen rikas elämä",""],
    ["Jääräpää Aku",""],
    ["Mikki ja Eka Vekara",""],
    ["Roope ui rahoissa",""],
    ["Rahanero Roope",""],
    ["Ankkain sankka suku",""],
    ["Taikaviitan tähtihetket",""],
    ["Älä hellitä, Aku",""],
    ["Juhlakalu Aku",""],
    ["Maailman rikkain ankka",""],
    ["Riemua riittää",""],
    ["Preerian laulu",""],
    ["Aku saa aikaan",""],
    ["Menestyksen maku",""],
    ["Iines tykkää Akusta",""],
    ["Olympialaisten aika",""],
    ["Touhua ja tohinaa!",""],
    ["Tietä Akulle!",""],
    ["Roope ajaa täysillä",""],
    ["Ankkalinnan ralli",""],
    ["Toivekonsertti",""],
    ["Loikkien lomalle",""],
    ["Akun viemää",""],
    ["Akun nuorallatanssi",""],
    ["Aku kaukomailla",""],
    ["Juhlaparaati",""],
    ["Yli kivien ja kantojen",""],
    ["Taikaviitalle tapahtuu",""],
    ["Roope Ankka lennossa",""],
    ["Tietä Taikaviitalle",""],
    ["Aku kohtalon kolhuissa",""],
    ["Ankat oikopolulla",""],
    ["Rahasade ei kastele",""],
    ["Taikaviittaa ei petetä",""],
    ["Mikistä on moneksi",""],
    ["Tähtien takana",""],
    ["Roopen päätä ei palele",""],
    ["Joron jäljillä",""],
    ["Tarua vai totta?",""],
    ["Pahemmassa kuin pulassa",""],
    ["Sulaa kultaa",""],
    ["Rahatynnyri",""],
    ["Akun lokoisa loma",""],
    ["Roope menee lujaa",""],
    ["Ikuinen kakkonen",""],
    ["Masalian tiikeri",""],
    ["Salaperäiset kyntteliköt",""],
    ["Taikaviitta ja Kumi-Kalle",""],
    ["Roope ja rahahirviö",""],
    ["Roopen unelmat",""],
    ["Antiikin ihmeet",""],
    ["Avaruuden armoilla",""],
    ["Joka tietoa lisää...",""],
    ["Räpylät rannalle, Aku",""],
    ["Luonnon helmassa",""],
    ["Vauhdilla vaaroihin",""],
    ["Nyt tarkkana!",""],
    ["Lassoleikit",""],
    ["Runsauden sarvi","Juhlanumero - 288 sivua"],
    ["Konstit on monet",""],
    ["Tämäkin vielä!",""],
    ["Akun lomamuistot",""],
    ["Nyt nappaa!",""],
    ["Mutkat suoriksi!",""],
    ["Kaidalla tiellä",""],
    ["Sydän paikallaan",""],
    ["Yli esteiden",""],
    ["Haavi auki!",""],
    ["Monta rautaa tulessa",""],
    ["Ruuvit löysällä",""],
    ["Koira vieköön!",""],
    ["Siipiveikkojen suosikki",""],
    ["Luonnon ihmeitä",""],
    ["Yökyöpeli",""],
    ["Tuulta purjeisiin",""],
    ["Talttumaton Taikaviitta",""],
    ["Lähdetään lätkimään",""],
    ["Törmäyskurssilla",""],
    ["Vahvan markan mies",""],
    ["Kovaa ja korkealta",""],
    ["Operaatio Kaktus",""],
    ["Säästölinjalla",""],
    ["Taikaviitan talouskriisi",""],
    ["Juhlan paikka",""],
    ["Ankallissankari","Tuplataskari (512 sivua)"],
    ["Helppo nakki",""],
    ["Joku odottaa soittoasi",""],
    ["Villaa ylle",""],
    ["Kova luu",""],
    ["Aina jaloissa",""],
    ["Rantaleijona","Tuplataskari (512 sivua)"],
    ["Hetki lyö",""],
    ["Aallokko kutsuu",""],
    ["Neljännesvuosisadan kakku",""],
    ["Oppia ikä kaikki",""],
    ["Vedet silmissä",""],
    ["Ankkaenergiaa","Tuplataskari (512 sivua)"],
    ["Eväät levällään",""],
    ["Päin seiniä",""],
    ["Kielletty hedelmä",""],
    ["Täältä pesee!",""],
    ["Kuumat paikat",""],
    ["Linssilude","Tuplataskari (512 sivua)"],
    ["Liimanäppi",""],
    ["Voitto kotiin!",""],
    ["Filmi poikki",""],
    ["Kylmä kylpy",""],
    ["Hirvibongari",""],
    ["Näköispatsas","Tuplataskari (512 sivua)"],
    ["Salaiset kansiot",""],
    ["Yövartija",""],
    ["Läpilasku",""],
    ["Tähtitakuu",""],
    ["Ykkösketju",""],
    ["Älä jännitä, Aku!",""],
    ["Listaykkönen","Tuplataskari (512 sivua)"],
    ["Rantaremmi",""],
    ["Tuplatällit",""],
    ["Ykköset yllä",""],
    ["Käry kävi!",""],
    ["Synttäriyllätys",""],
    ["Juhlaraha","Tuplataskari (512 sivua)"],
    ["Hiihtopummi",""],
    ["Pöytä koreaksi",""],
    ["Soita minulle, Aku!",""],
    ["Seuraa johtajaa",""],
    ["Älä tykkää kyttyrää",""],
    ["Nokkamies","Tuplataskari (512 sivua)"],
    ["Letkujenkka",""],
    ["Kyllä leikkaa!",""],
    ["Kauniita unia",""],
    ["Paalupaikka",""],
    ["Kevyellä linjalla",""],
    ["Kuokkavieras","Tuplataskari (512 sivua)"],
    ["Löysät pois",""],
    ["Suksi kuuseen!",""],
    ["Hurja joukko",""],
    ["Sakkorysä",""],
    ["Pellit auki",""],
    ["Kesätoimittaja","Tuplataskari (512 sivua)"],
    ["Pokkana vaan",""],
    ["Oksat pois",""],
    ["Intiaanikesä",""],
    ["Taidepaukku",""],
    ["Taivaan täydeltä",""],
    ["Ammattiauttaja","Tuplataskari (512 sivua)"],
    ["Se siitä!",""],
    ["Palo hallussa",""],
    ["Viime tipassa",""],
    ["Nokkakoriste",""],
    ["Äimän käkenä",""],
    ["Viimeinen pisara",""],
    ["Turistiluokka","Tuplataskari (512 sivua)"],
    ["Terävä veto",""],
    ["Veskarille kenkää",""],
    ["Hopeinen kuu",""],
    ["Räjähtävä tempaus",""],
    ["Salaliitto",""],
    ["Varttitonni","Tuplataskari (512 sivua)"],
    ["Kolmiodraama",""],
    ["Hammaspeikko lannistuu",""],
    ["Lintubongari",""],
    ["Varavarjo",""],
    ["Tyyris tyyli",""],
    ["Laivastovierailu",""],
    ["Täyttä elämää","Tuplataskari (512 sivua)"],
    ["Yhtä kyytiä",""],
    ["Taikaviitta kuilun partaalla",""],
    ["Pohjakosketus",""],
    ["Kapteeni käskee",""],
    ["Kauniit ja vihreät",""],
    ["Oloneuvos","Tuplataskari (512 sivua)"],
    ["Käteinen kiertoon",""],
    ["Isojalan jäljillä",""],
    ["Kalliovuorten kauhu",""],
    ["Räyhä maassa",""],
    ["Julma huvi",""],
    ["Matkaeväs","Tuplataskari (512 sivua)"],
    ["Pistämätön piilokärki",""],
    ["Kovaa valuuttaa",""],
    ["Vesiliirto",""],
    ["Henki korkealla",""],
    ["Polttava ongelma",""],
    ["Luunelonen","Tuplataskari (512 sivua)"],
    ["Virusvaroitus",""],
    ["Harmaan talouden harmit",""],
    ["Kauhukabiini",""],
    ["Rottasota",""],
    ["Mustan kuulan maa",""],
    ["Kerran kuussa","Tuplataskari (512 sivua)"],
    ["Nuukalaislegioona",""],
    ["Uhmaikä",""],
    ["Pikkujättiläinen",""],
    ["Hui hai!","Tuplataskari (512 sivua)"],
    ["Merten kauhu",""],
    ["Totta vai tarua",""],
    ["Kiinalainen juttu",""],
    ["Poikki ja pinoon",""],
    ["Oikotie onneen",""],
    ["Pahanilmanlinnut",""],
    ["Palvelu pelaa",""],
    ["Epäilyksen varjo","Tuplataskari (512 sivua)"],
    ["Konille kyytiä",""],
    ["Maanalainen mullistus",""],
    ["Melkein mestari",""],
    ["Tähtikaksikko","Tuplataskari (512 sivua)"],
    ["Venyy ja paukkuu",""],
    ["Uutispommi",""],
    ["Kolmesataa","312 sivua"],
    ["Lupa livistää",""],
    ["Haamulinnan pamaus",""],
    ["Ääni ja vimma",""],
    ["Meksikon multakurkku",""],
    ["Tuulihattu","Tuplataskari (512 sivua)"],
    ["Ilmojen halki",""],
    ["Kova pala purtavaksi",""],
    ["Kaksin aina kaunihimpi",""],
    ["Tähtien setä","Tuplataskari (512 sivua)"],
    ["Silmät selässä",""],
    ["Tuhannen taalan paikka",""],
    ["Kaikilla mausteilla",""],
    ["Kaikki tiet vievät Ankkalinnaan",""],
    ["Likaista peliä",""],
    ["Asu vapaa",""],
    ["Tuli ja leimaus!",""],
    ["Terveisiä Ankkalinnasta","Tuplataskari (512 sivua)"],
    ["Mars kentälle!",""],
    ["Miljoonakaappaus",""],
    ["Raha rauhoittaa",""],
    ["Noitakonsti","Tuplataskari (512 sivua)"],
    ["Jaettu ilo",""],
    ["Yövuoro",""],
    ["Kalmanlehdon kartano",""],
    ["Turistirysäys",""],
    ["Vanha uskollinen",""],
    ["Menneisyyden vanki",""],
    ["Nokkapokka",""],
    ["Roope-sedän rahanippu","Tuplataskari (512 sivua)"],
    ["Kesä kaikilla",""],
    ["Piraattipuisto",""],
    ["Ihan tavallinen sankari",""],
    ["Kolmoset","Tuplataskari (512 sivua)"],
    ["Kylmää kyytiä",""],
    ["Kuutamokeikka",""],
    ["Kultakuorrutus",""],
    ["Onni potkii",""],
    ["Oma maa mansikka",""],
    ["Hetki lyö",""],
    ["Äkkilähtö",""],
    ["Läpimurto","Tuplataskari (512 sivua)"],
    ["Saksipotku",""],
    ["Pintaa syvemmälle",""],
    ["Samassa veneessä",""],
    ["Tähtihetki","Tuplataskari (512 sivua)"],
    ["Lantti lainassa",""],
    ["Sankarainesta",""],
    ["Paluu Karhuvuorelle",""],
    ["Kassavirta",""],
    ["Vuosisadan rakkaustarina",""],
    ["Tuplanolla ja petosten kehä",""],
    ["Velvollisuus kutsuu",""],
    ["Onnenonkija","Tuplataskari (512 sivua)"],
    ["Pallo hallussa",""],
    ["Paikka auringossa",""],
    ["Operaatio Lepo",""],
    ["Varjo yössä","Tuplataskari (512 sivua)"],
    ["Tuplanolla ja kohtalokas ensi-ilta",""],
    ["Täyttä rautaa",""],
    ["Painovirhe",""],
    ["Salattu elämä",""],
    ["Haluatko triljonääriksi?",""],
    ["Kultaa ja kunniaa","296 sivua"],
    ["Merkkimies",""],
    ["Tuplanolla ja syvyyden saalistajat","Tuplataskari (512 sivua)"],
    ["Kaikki pelissä",""],
    ["Ankkurit ylös!",""],
    ["Kuutamolla",""],
    ["Tripla","Triplataskari (768 sivua)"],
    ["Tukka hyvin",""],
    ["Kaikki likoon",""],
    ["Kuuhullut",""],
    ["Umpijäässä","Tuplataskari (512 sivua)"],
    ["Valiojoukko",""],
    ["Tuplanolla ja armoton ajojahti",""],
    ["Aikahyppy",""],
    ["Seitsemän meren kauhu","Tuplataskari (512 sivua)"],
    ["Muistin varassa",""],
    ["Rantakirppu",""],
    ["Jättiyllätys",""],
    ["Kolmoiselämää","Triplataskari (768 sivua)"],
    ["Näköalapaikka",""],
    ["Tuplanolla ja Amorin nuolet",""],
    ["Rahat mielessä",""],
    ["Hyvä tuli!","Tuplataskari (512 sivua)"],
    ["Tuplanolla ja pelin säännöt",""],
    ["Taidenautinto",""],
    ["Kultakypärä",""],
    ["Vahtivuoro","Tuplataskari (512 sivua)"],
    ["Outo lintu",""],
    ["Kaikki kannelle!",""],
    ["Tuplanolla ja Olympoksen arvoitus",""],
    ["Kultaharkko","Triplataskari (768 sivua)"],
    ["Kansikuvapoika",""],
    ["Lorun loppu",""],
    ["Jäljillä",""],
    ["Perhosvaikutus","Tuplataskari (512 sivua)"],
    ["Veden varassa",""],
    ["Pelin henki",""],
    ["Neljäsataa","400 sivua"],
    ["Tuplanolla ja uhka taivaalta","Tuplataskari (512 sivua)"],
    ["Fantom Ankan salaisuus",""],
    ["Kesän lapsi",""],
    ["Tuulitakki",""],
    ["Onni yksillä",""],
    ["Maltan ankka","Tuplataskari (512 sivua)"],
    ["Yön yrmy",""],
    ["Rahavirta ratkaisee",""],
    ["Sormuksen narrit","Tuplataskari (512 sivua)"],
    ["Muodin huipulla",""],
    ["Täyskaato",""],
    ["Juhlapäivä","400 sivua"],
    ["Tähtien setä: Vastaisku","Triplataskari (768 sivua)"],
    ["Kitupiikin kesätyö",""],
    ["Kipparitrio",""],
    ["Vaivan palkka",""],
    ["Pikavuoro",""],
    ["Hyvällä tuulella",""],
    ["Piirun verran parempi","Tuplataskari (512 sivua)"],
    ["Nokittaja",""],
    ["Tuhotrio",""],
    ["Sankarparvi","Tuplataskari (512 sivua)"],
    ["Viekasten kivi",""],
    ["Taustavoima",""],
    ["Kisaturisti","400 sivua"],
    ["Aina tiellä","Triplataskari (768 sivua)"],
    ["Tulilinjalla",""],
    ["Täyspakkaus",""],
    ["Myrskyvaroitus",""],
    ["Loma paketissa",""],
    ["Voimakaksikko",""],
    ["Kreivin aikaan","Tuplataskari (512 sivua)"],
    ["Valomerkki",""],
    ["Viitan mahti","400 sivua"],
    ["Takaisku","Tuplataskari (512 sivua)"],
    ["Viikinkien valtias",""],
    ["Kultakylpy",""],
    ["Polttopiste","400 sivua"],
    ["Kovin kolikko","Triplataskari (768 sivua)"],
    ["Uimamaisteri",""],
    ["Kesärenkaat",""],
    ["Paljunvartijat",""],
    ["Rio, ohoi!",""],
    ["Tuima tuimille",""],
    ["Ajokortti","Tuplataskari (512 sivua)"],
    ["Ihan hilkulla",""],
    ["Pärstäpankkiiri","400 sivua"],
    ["Napamies","Tuplataskari (512 sivua)"],
    ["Homma hanskassa",""],
    ["Kauhukaksikko",""],
    ["Kova koville","400 sivua"],
    ["Metsän poika","Tuplataskari (512 sivua)"],
    ["Grillihullut",""],
    ["Menolippu",""],
    ["Puolisukeltaja",""],
    ["Reissumies",""],
    ["Ihan ässä","Triplataskari (768 sivua)"],
    ["Perhonen vieköön",""],
    ["Juhlahetki","400 sivua"],
    ["Uhka ulapalta","Tuplataskari (512 sivua)"],
    ["Kadonneen suunnan metsästäjä",""],
    ["Kuppi kummaa",""],
    ["Täällä vartioin minä!","Tuplataskari (512 sivua)"],
    ["Valekyttä","400 sivua"],
    ["Torjuntavoitto",""],
    ["Kuha on hai",""],
    ["Hellehullu",""],
    ["Muumi­on kosto",""],
    ["768 karaattia","Triplataskari (768 sivua)"],
    ["Laboratorion noutaja",""],
    ["Mokia 471","400 sivua"],
    ["Onnen lantit","Tuplataskari (512 sivua)"],
    ["Astu harhaan",""],
    ["Tulen ja jään",""],
    ["Kostajan jäljillä","400 sivua"],
    ["Rytmi veressä",""],
    ["Onnea!","Triplataskari (768 sivua)"],
    ["Nilkit nippuun, Taikaviitta",""],
    ["Pieni askel ankalle","400 sivua"],
    ["Titaanien taistelu",""],
    ["Tuplanolla maailma on omillaan","Tuplataskari (512 sivua)"],
    ["Kelmeistä katalin",""],
    ["Hirmuliskojen yö","400 sivua"],
    ["Tuhon temppeli",""],
    ["Valhallan vaara",""],
    ["Miljoonasade",""],
    ["Pahan kourissa",""],
    ["Onnen päivät",""],
    ["Löylynlyömä",""],
    ["Korpikuoro",""],
    ["Tie vie",""],
    ["Suuri munaryöstö",""],
    ["Vain yhden lantin tähden",""],
    ["Suuri kutistus",""],
    ["Taivahan talikynttilät!",""],
    ["Muikku!",""],
    ["Hupia horisontissa",""],
    ["Parhaat kaverit",""],
    ["Mestarikuski",""],
    // 500
    ["Viissatanen",""],
    ["Kisapaikka",""],
    ["Kesäterässä",""],
    ["Mitalitoivot",""],
    ["Seikkailujen saari",""],
    ["Laavaa!",""],
    ["Virtaa Akusta",""],
    ["Kakkukopla",""],
    ["Kaamoksen kunkku",""],
    ["Vikavippi",""],
    ["Lukuräyhä",""],
    ["Hutihattara",""],
    ["Aikamatkat",""],
    ["Loma!",""],
    ["Molskis!",""],
    ["Ihan helmi",""],
    ["Pennonen ajatuksistasi",""],
    ["Yön ruhtinas",""],
    ["Pikkupojat",""],
    ["Ykköstykki",""],
    ["Onnen poikia",""],
    ["Kokkisotku",""],
    ["Vaarojen viidakko",""],
    ["Yölintu",""],
    ["Puskajuhlat",""],
    ["Riippumaton ritari",""],
    ["Lomaraha",""],
    ["Kartalla?",""],
    ["Rapakuntoon!",""],
    ["Hyvät, rahat ja rumat",""],
    ["Haamunkoitto",""],
    ["Tähdet kertovat",""],
    ["Kullanmurut",""],
    ["Junantuomat",""],
    ["Multakurkku","Kääntökirja (sisältää 64 lisäsivua: Kolumbusperhon aarrekartta)"],
    ["Hiiohoi!",""],
    ["Kalsarisankari",""],
    ["Kärkkäri",""],
    ["Laiturin nokat",""],
    ["Ylilyönti",""],
    ["Peliepeli","Kääntökirja (sisältää 64 sivua Aku Taikaviitta taskukirjasta)"],
    ["Kultaryntäys",""],
    ["Huutokauppakeikari",""],
    ["Vasta vihdottu",""],
    ["Kuusessa",""],
    ["Halki, poikki ja dinoon",""],
    ["Romuralli",""],
    ["Pyykkipäivä",""],
    ["Traktorilla tavataan",""],
    ["Hyttystyrkky",""],
    ["Kumiankat",""],
    ["Vorovyöry",""],
    ["Ankallismaisema",""],
    ["Sankaritrio",""],
    ["Keskiyön kauhut",""],
    ["Poroskooppi",""],
    ["Oopperan kummitus",""],
    ["Kuplakylpy",""],
    ["Kivenkova",""],
    ["Entten tentten", ""],
    // 560
    ["Miljardöörin matkakirja",""],
    ["Nappulaliiga",""],
    ["Lomalle lompsis",""],
    ["Aurinkotervehdys",""],
    ["Sormuksen kirous",""]
]

const mr_partial_data = [
    {
        id: "1982A12",
        ti: "Lentävä hollantilainen",
        st: "Tilaajalahja"
    },
    {
        id: "1983A12",
        ti: "Kääpiöintiaanit",
        st: "Tilaajalahja"
    },
    {
        id: "1987A12",
        ti: "Takaisin Klondikeen",
        st: "Tilaajalahja"
    },
    {
        id: "1988B12",
        ti: "Rahamassi",
        st: "Tilaajalahja"
    },
    {
        id: "1989B12",
        ti: "Voi mammona!",
        st: "Tilaajalahja"
    },
    {
        id: "1991B12",
        ti: "Takaisin Xanaduun",
        st: "Tilaajalahja"
    },
    {
        id: "1992B12",
        ti: "Raha ei haise",
        st: "Tilaajalahja"
    },
    {
        id: "1993B12",
        ti: "Rikkana rokassa",
        st: "Tilaajalahja"
    },
/*  // JULISTE
    {
        id: "1994B12",
        ti: "Viimeinen suuri seikkailija",
        st: "Tilaajalahja"
    },
*/
/*  // JULISTE
    {
        id: "1995B12",
        ti: "Black Gold, Yellow Gold",
        st: "Tilaajalahja"
    },
*/
    {
        id: "1995NL",
        ti: "Näytelehti",
        st: "Näytelehti"
    },
    {
        id: "1996-KH",
        ti: "Kultaharkko",
        st: "Kovakantinen vuosikerta nro 1. Sisältää Roope-Sedät 01/1978, 02/1978, 03/1978, 04/1978",
    },
    {
        id: "1997-VIS",
        ti: "Visukintun vuosikymmenet 1947-1997",
        st: "Juhlistaa Roope Ankan 50-vuotista taivalta"
    },
    {
        id: "1999B06",
        ti: "Roope-Setä (mietelausevihko)",
        st: "Julkaistu Roope-Setä nro 238 mukana"
    },
    {
        id: "2000E",
        ti: "Visukintun kielikylpy",
        st: "Englanninoppia Roope Ankan siivellä"
    },
    {
        id: "2001E",
        ti: "Visukintun kielikylpy 2",
        st: "Englanninoppia Ankan siivellä (all stories in English with short glossary in Finnish)"
    },
    {
        id: "2002E",
        ti: "Visukintun kielikylpy 3",
        st: "Englanninoppia Roope Ankan siivellä"
    },
    {
        id: "2003-KKK",
        ti: "Konnia, ketkuja ja konkursseja",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2003E",
        ti: "Visukintun kielikylpy 4",
        st: "Englanninoppia Roope Ankan siivellä"
    },
    {
        id: "2004-MMI",
        ti: "Maalla, merellä ja ilmassa",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2005-OOO",
        ti: "Osakkeita, optioita ja onnenonkijoita",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2006-SSS",
        ti: "Sankareita, salaliittolaisia ja sudenkuoppia",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2007-JR",
        ti: "Juhlaraha",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2008-LP",
        ti: "Likainen puolitusina",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2008N1978",
        ti: "Roope-Setä 1/1978 (näköispainosliite)",
        st: "Julkaistu Roope-Setä nro 341 mukana"
    },
    {
        id: "2009-SK",
        ti: "Sankareita kaikki",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2010-RR",
        ti: "Roope on aina Roope",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2011-RRR",
        ti: "Rikas, rikkaampi, Roope",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2012-RVK",
        ti: "Roope vastaan Kroisos",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2013-MR",
        ti: "Mestarillinen Roope",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2014-KK",
        ti: "Kitupiikkien kuningas",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2015-PK",
        ti: "Puhtaana käteen",
        st: "Lahja uusille tilaajille"
    },
    {
        id: "2016-SR",
        ti: "Sikarikas",
        st: "Lahja uusille tilaajille"
    }

]

/* Teema */
const tt_partial_data = [
    /* id: AATT++1, co: aatt-1.jpg */
    [ "Pala Kakkua","2001" ],
    [ "Tutkivaa journalismia","2001" ],
    [ "Hattutemppu","2002" ],
    [ "Munaaja","2002" ],
    [ "Velhojen valtakunta","2003" ],
    [ "Rekiretki","2003" ],
    [ "Kääk!","2004" ],
    [ "Kultainen joulu","2004" ],
    [ "Valkokankaan sankarit","2005" ],
    [ "Pakettimatka","2005" ],
    [ "Banzai","2006" ],
    [ "Lahjajahti","2006" ],
    [ "Nimeni on Ankka, Aku Ankka","2007" ],
    [ "Laki ja järjestys","2007" ],
    [ "Puhu pukille","2007" ],
    [ "Munaajan paluu","2008" ],
    [ "Kelmien kerho","2008" ],
    [ "Lahjaunelmia","2008" ],
    [ "Kaksoiselämää","2009" ],
    [ "Tuhat ja yksi työtä","2009" ],
    [ "Todellisia tonttuja","2009" ],
    [ "Sohvaperuna","2010" ],
    [ "Ultrasankarit vs. Paha Seiska","2010" ],
    [ "Joulun taikaa","2010" ],
    [ "Munaajan veljenpoika","2011" ],
    [ "Kultakuume","2011" ],
    [ "Pehmeä paketti","2011" ],
    [ "Urku auki!","2012" ],
    [ "Kymppipaikka","2012" ],
    [ "Joulun tähdet","2012" ],
    [ "Salaiset aseet","2013" ],
    [ "Ensilantti","2013" ],
    [ "Tuutin täydeltä","2013" ],
    [ "Tunteiden tulkki","2013" ],
    [ "Pukin pallopoika","2013" ],
    [ "Minä, robotti","2013" ],
    [ "Täyttä timanttia","2014" ],
    [ "Älypeli","2014" ],
    [ "Pim!","2014" ],
    [ "Kuusijuhlan tähti","2014" ],
    [ "Piraatteja ja pikipöksyjä","2015" ],
    [ "Köyhät ritarit","2015" ],
    [ "Pieni askel ankalle","2015" ],
    [ "Tähtituisku","2015" ],
    [ "Antikkin sankari","2016" ],
    [ "Maalitykki","2016" ],
    [ "Inkojen suursaituri","2016" ],
    [ "Aaton sankari","2016" ],
    [ "Juhlakattaus","2017" ],
    [ "Piraatin palkkapäivä","2017" ],
    [ "Pääoma","2017" ],
    [ "Joulun valot","2017" ],
    [ "Luola-ankkojen klaani","2018" ],
    [ "Don Zorro","2018" ]

]

/* Super */
const ts_partial_data = [
/* id: AAST++1, co: aast-1.jpg*/
    [ "Sankaruus kunniaan","2014" ],
    [ "Vaaroja päin","2014" ],
    [ "Yön herra","2015" ],
    [ "Myrskyvaroitus","2015" ],
    [ "Haukan katse","2016" ],
    [ "Tuhon uhka","2016" ],
    [ "Virusvahti","2017" ],
    [ "Valvoja","2017" ],
    [ "Läpimurto","2018" ],
    [ "Ukkosisku","2018" ],
    [ "Teräsnyrkki","2019" ],
    [ "Lopun alku","2019" ]
]

const tp_partial_data = [
    {
        id: "2015TK",
        na: "Taskarispesiaali",
        ti: "Täyskäki",
        st: ""
    },
    {
        id: "2016LL",
        na: "Taskarispesiaali",
        ti: "N:o 436 1/2 - Lamalääke",
        st: ""
    },
    {
        id: "2016FS",
        na: "Taskarin futisspesiaali",
        ti: "Kolmosvoitto",
        st: ""
    },
    {
        id: "2016MP",
        na: "Taskarispesiaali",
        ti: "Munaajan parhaat",
        st: ""
    },
    {
        id: "2017PP",
        na: "Taskarispesiaali",
        ti: "N:o 449 1/2 - Peli poikki",
        st: ""
    },
    {
        id: "2017KN",
        na: "Taskarin koodausspesiaali",
        ti: "Kosketusnäyttö",
        st: ""
    },
    {
        id: "2017KS",
        na: "Taskarin kesäspesiaali",
        ti: "Vesipeto",
        st: ""
    },
    {
        id: "2018KT",
        na: "Taskarin kevätspesiaali",
        ti: "Setiä ja serkkuja",
        st: ""
    },
    {
        id: "2018KS",
        na: "Taskarin kesäspesiaali",
        ti: "Riemuloma",
        st: ""
    },
    {
        id: "2018RT",
        na: "Rokki-Taskari",
        ti: "Turmion räpylät",
        st: ""
    },
    {
        id: "2018JT",
        na: "Joulu-Taskari",
        ti: "Joulun jättipotti",
        st: ""
    },
    {
        id: "2019JU",
        na: "Juhla-Taskari",
        ti: "Ykkösankka",
        st: ""
    },
    {
        id: "2019HT",
        na: "Huussi-Taskari",
        ti: "Täysistunto",
        st: ""
    },
    {
        id: "2019RS",
        na: "Rötös-Taskari",
        ti: "Mustakaapu",
        st: ""
    },
    {
        id: "2019JT",
        na: "Joulu-Taskari",
        ti: "Hyvää joulua!",
        st: ""
    },
    {
        id: "2020FT",
        na: "Futis-Taskari",
        ti: "Pöllö peliin!",
        st: ""
    },
    {
        id: "2020UT",
        na: "Urheilu-Taskari",
        ti: "Hutikuti",
        st: ""
    },
    {
        id: "2020TK",
        na: "Taskarispesiaali",
        ti: "Täyttä kultaa",
        st: ""
    },
    {
        id: "2020AM",
        na: "Taskarispesiaali",
        ti: "Ankkalinnan mestarivarkaat",
        st: ""
    },
    {
        id: "2020ET",
        na: "Egypti-Taskari",
        ti: "Matkaopas Egyptiin",
        st: ""
    },
    {
        id: "2020JT",
        na: "Joulu-Taskari",
        ti: "Joululahja",
        st: ""
    },
    {
        id: "2020FY",
        na: "Fyffe-Taskari",
        ti: "Haluatko triljonääriksi?",
        st: ""
    },
    {
        id: "2021ST",
        na: "Sankari-Taskari",
        ti: "Arjen supersankarit",
        st: ""
    },
    {
        id: "2021RT",
        na: "Reissu-Taskari",
        ti: "Seikkailijan opas",
        st: ""
    },
    {
        id: "2021AT",
        na: "Ankanpojat-Taskari",
        ti: "Voi veljet!",
        st: ""
    },
    {
        id: "2021JT",
        na: "Joulu-Taskari",
        ti: "Pakettiratkaisu",
        st: ""
    },
    {
        id: "2021KT",
        na: "Konna-Taskari",
        ti: "Hymyä!",
        st: ""
    },
    {
        id: "2022KT",
        na: "Kulkupeli-Taskari",
        ti: "Menomankeli",
        st: ""
    },
    {
        id: "2022ST",
        na: "Sudenpentu-Taskari",
        ti: "P.Ä.Ä.J.E.H.U.T.",
        st: ""
    },
    {
        id: "2022RT",
        na: "Retkeily-Taskari",
        ti: "Hupulla tuulee",
        st: ""
    },
    {
        id: "2022JT",
        na: "Joulu-Taskari",
        ti: "Joulu on taas",
        st: ""
    },
    {
        id: "2022AE",
        na: "Taskarispesiaali",
        ti: "Ankalliseepos",
        st: ""
    },
    {
        id: "2023MA",
        na: "Taskarispesiaali",
        ti: "Minä Aku",
        st: ""
    },
    {
        id: "2023AA",
        na: "Taskarispesiaali",
        ti: "Astu Ankkalinnaan",
        st: ""
    },
    {
        id: "2023AD",
        na: "Taskarispesiaali",
        ti: "Ankkadynastia",
        st: "Tuplataskari (512 sivua)"
    },
    {
        id: "2023EL",
        na: "Taskarispesiaali",
        ti: "Ensilantti",
        st: ""
    },
    {
        id: "2023JT",
        na: "Joulu-Taskari",
        ti: "Joulun tähti",
        st: ""
    },
    {
        id: "2023KK",
        na: "Taskarispesiaali",
        ti: "Kuka kukin on?",
        st: ""
    },
    {
        id: "2024MR",
        na: "Taskarispesiaali",
        ti: "Minä Roope",
        st: ""
    },
    {
        id: "2024ST",
        na: "Sportti-Taskari",
        ti: "Urheiluruutu",
        st: ""
    },
    {
        id: "2024LT",
        na: "Leffa-Taskari",
        ti: "Ankka vailla menneisyyttä / Elävän kuvan taika",
        st: "Kääntökirja"
    },
    {
        id: "2024SK",
        na: "Taskarispesiaali",
        ti: "Sudenpentujen käsikirja",
        st: ""
    },
    {
        id: "2024JK",
        na: "Taskarispesiaali",
        ti: "Joulukalenteri",
        st: ""
    },
    {
        id: "2024SN",
        na: "Taskarispesiaali",
        ti: "Sätkynukke",
        st: ""
    },
    { 
        id: "2025PT",
        na: "Pressi-Taskari",
        ti: "Ilta-Pulu",
        st: ""
    },
    { 
        id: "2025DT",
        na: "Dekkari-Taskari",
        ti: "Nuuskija",
        st: ""
    },
    { 
        id: "2025RK",
        na: "Taskarispesiaali",
        ti: "Rokkikukot",
        st: ""
    },
    { 
        id: "2025RT",
        na: "Ritari-Taskari",
        ti: "Sir Aku",
        st: ""
    },
    { 
        id: "2025JT",
        na: "Taskarispesiaali",
        ti: "Joulun taikaa",
        st: ""
    },
    { 
        id: "2025AA",
        na: "Taskarispesiaali",
        ti: "Akun ammatit",
        st: ""
    },
    {
        id: "2026TT",
        na: "Taide-Taskari",
        ti: "Ankallisgalleria",
        st: ""
    },
    {
        id: "2026RT",
        na: "Reissu-Taskari",
        ti: "Karttapalloilijat",
        st: ""
    },
    {
        id: "2026ST",
        na: "Sportti-Taskari",
        ti: "Sporttivartti",
        st: ""
    }

]

const rs_partial_data =
[
    [   "1978-1","Roope-Setä taskulehti 1" ],
    [   "1978-2","Roope-Setä taskulehti 2" ],
    [   "1978-3","Roope-Setä taskulehti 3" ],
    [   "1978-4","Roope-Setä taskulehti 4" ],
    [   "1979-1","Roope-Setä taskulehti 5" ],
    [   "1979-2","Roope-Setä taskulehti 6" ],
    [   "1979-3","Roope-Setä taskulehti 7" ],
    [   "1979-4","Roope-Setä taskulehti 8" ],
    [   "1979-5","Roope-Setä taskulehti 9" ],
    [   "1979-6","Roope-Setä taskulehti 10" ],
    [   "1980-1","Roope-Setä taskulehti 11" ],
    [   "1980-2","Roope-Setä taskulehti 12" ],
    [   "1980-3","Roope-Setä taskulehti 13" ],
    [   "1980-4","Roope-Setä taskulehti 14" ],
    [   "1980-5","Roope-Setä taskulehti 15" ],
    [   "1980-6","Roope-Setä taskulehti 16" ],
    [   "1981-1","Roope-Setä taskulehti 17" ],
    [   "1981-2", "Roope-Setä taskulehti 18" ],
    [   "1981-3", "Roope-Setä taskulehti 19" ],
    [   "1981-4", "Roope-Setä taskulehti 20" ],
    [   "1981-5", "Roope-Setä taskulehti 21" ],
    [   "1981-6", "Roope-Setä taskulehti 22" ],
    [   "1981-7", "Roope-Setä taskulehti 23" ],
    [   "1981-8", "Roope-Setä taskulehti 24" ],
    [   "1981-9", "Roope-Setä taskulehti 25" ],
    [   "1981-10", "Roope-Setä taskulehti 26" ],
    [   "1981-11", "Roope-Setä taskulehti 27" ],
    [   "1981-12","Roope-Setä taskulehti 28"],
    [   "1982-1","Roope-Setä taskulehti 29"],
    [   "1982-2", "Roope-Setä taskulehti 30" ],
    [   "1982-3", "Roope-Setä taskulehti 31" ],
    [   "1982-4", "Roope-Setä taskulehti 32" ],
    [   "1982-5", "Roope-Setä taskulehti 33" ],
    [   "1982-6", "Roope-Setä taskulehti 34" ],
    [   "1982-7", "Roope-Setä taskulehti 35" ],
    [   "1982-8", "Roope-Setä taskulehti 36" ],
    [   "1982-9", "Roope-Setä taskulehti 37" ],
    [   "1982-10", "Roope-Setä taskulehti 38" ],
    [   "1982-11", "Roope-Setä taskulehti 39" ],
    [   "1982-12", "Roope-Setä taskulehti 40" ],
    [   "1983-1", "Roope-Setä taskulehti 41" ],
    [   "1983-2", "Roope-Setä taskulehti 42" ],
    [   "1983-3", "Roope-Setä taskulehti 43" ],
    [   "1983-4", "Roope-Setä taskulehti 44" ],
    [   "1983-5", "Roope-Setä taskulehti 45" ],
    [   "1983-6", "Roope-Setä taskulehti 46" ],
    [   "1983-7", "Roope-Setä taskulehti 47" ],
    [   "1983-8", "Roope-Setä taskulehti 48" ],
    [   "1983-9", "Roope-Setä taskulehti 49" ],
    [   "1983-10", "Roope-Setä taskulehti 50" ],
    [   "1983-11", "Roope-Setä taskulehti 51" ],
    [   "1983-12", "Roope-Setä taskulehti 52" ],
    [   "1984-1", "Roope-Setä taskulehti 53" ],
    [   "1984-2", "Roope-Setä taskulehti 54" ],
    [   "1984-3", "Roope-Setä taskulehti 55" ],
    [   "1984-4", "Roope-Setä taskulehti 56" ],
    [   "1984-5", "Roope-Setä taskulehti 57" ],
    [   "1984-6", "Roope-Setä taskulehti 58" ],
    [   "1984-7", "Roope-Setä taskulehti 59" ],
    [   "1984-8", "Roope-Setä taskulehti 60" ],
    [   "1984-9", "Roope-Setä taskulehti 61" ],
    [   "1984-10", "Roope-Setä taskulehti 62" ],
    [   "1984-11", "Roope-Setä taskulehti 63" ],
    [   "1984-12", "Roope-Setä taskulehti 64" ],
    [   "1985-1", "Roope-Setä taskulehti 65" ],
    [   "1985-2", "Roope-Setä taskulehti 66" ],
    [   "1985-3", "Roope-Setä taskulehti 67" ],
    [   "1985-4", "Roope-Setä 68" ],
    [   "1985-5", "Roope-Setä 69" ],
    [   "1985-6", "Roope-Setä 70" ],
    [   "1985-7", "Roope-Setä 71" ],
    [   "1985-8", "Roope-Setä 72" ],
    [   "1985-9", "Roope-Setä 73" ],
    [   "1985-10", "Roope-Setä 74" ],
    [   "1985-11", "Roope-Setä 75" ],
    [   "1985-12", "Roope-Setä 76" ],
    [   "1986-1", "Roope-Setä 77" ],
    [   "1986-2", "Roope-Setä 78" ],
    [   "1986-3", "Roope-Setä 79" ],
    [   "1986-4", "Roope-Setä 80" ],
    [   "1986-5", "Roope-Setä 81" ],
    [   "1986-6", "Roope-Setä 82" ],
    [   "1986-7", "Roope-Setä 83" ],
    [   "1986-8", "Roope-Setä 84" ],
    [   "1986-9", "Roope-Setä 85" ],
    [   "1986-10", "Roope-Setä 86" ],
    [   "1986-11", "Roope-Setä 87" ],
    [   "1986-12", "Roope-Setä 88" ],
    [   "1987-1", "Roope-Setä 89" ],
    [   "1987-2", "Roope-Setä 90" ],
    [   "1987-3", "Roope-Setä 91" ],
    [   "1987-4", "Roope-Setä 92" ],
    [   "1987-5", "Roope-Setä 93" ],
    [   "1987-6", "Roope-Setä 94" ],
    [   "1987-7", "Roope-Setä 95" ],
    [   "1987-8", "Roope-Setä 96" ],
    [   "1987-9", "Roope-Setä 97" ],
    [   "1987-10", "Roope-Setä 98" ],
    [   "1987-11", "Roope-Setä 99" ],
    [   "1987-12", "Roope-Setä 100" ],
    [   "1988-1", "Roope-Setä 101" ],
    [   "1988-2", "Roope-Setä 102" ],
    [   "1988-3", "Roope-Setä 103" ],
    [   "1988-4", "Roope-Setä 104" ],
    [   "1988-5", "Roope-Setä 105" ],
    [   "1988-6", "Roope-Setä 106" ],
    [   "1988-7", "Roope-Setä 107" ],
    [   "1988-8", "Roope-Setä 108" ],
    [   "1988-9", "Roope-Setä 109" ],
    [   "1988-10", "Roope-Setä 110" ],
    [   "1988-11", "Roope-Setä 111" ],
    [   "1988-12", "Roope-Setä 112" ],
    [   "1989-1", "Roope-Setä 113" ],
    [   "1989-2", "Roope-Setä 114" ],
    [   "1989-3", "Roope-Setä 115" ],
    [   "1989-4", "Roope-Setä 116" ],
    [   "1989-5", "Roope-Setä 117" ],
    [   "1989-6", "Roope-Setä 118" ],
    [   "1989-7", "Roope-Setä 119" ],
    [   "1989-8", "Roope-Setä 120" ],
    [   "1989-9", "Roope-Setä 121" ],
    [   "1989-10", "Roope-Setä 122" ],
    [   "1989-11", "Roope-Setä 123" ],
    [   "1989-12", "Roope-Setä 124" ],
    [   "1990-1", "Roope-Setä 125" ],
    [   "1990-2", "Roope-Setä 126" ],
    [   "1990-3", "Roope-Setä 127" ],
    [   "1990-4", "Roope-Setä 128" ],
    [   "1990-5", "Roope-Setä 129" ],
    [   "1990-6", "Roope-Setä 130" ],
    [   "1990-7", "Roope-Setä 131" ],
    [   "1990-8", "Roope-Setä 132" ],
    [   "1990-9", "Roope-Setä 133" ],
    [   "1990-10", "Roope-Setä 134" ],
    [   "1990-11", "Roope-Setä 135" ],
    [   "1990-12", "Roope-Setä 136" ],
    [   "1991-1", "Roope-Setä 137" ],
    [   "1991-2", "Roope-Setä 138" ],
    [   "1991-3", "Roope-Setä 139" ],
    [   "1991-4", "Roope-Setä 140" ],
    [   "1991-5", "Roope-Setä 141" ],
    [   "1991-6", "Roope-Setä 142" ],
    [   "1991-7", "Roope-Setä 143" ],
    [   "1991-8", "Roope-Setä 144" ],
    [   "1991-9", "Roope-Setä 145" ],
    [   "1991-10", "Roope-Setä 146" ],
    [   "1991-11", "Roope-Setä 147" ],
    [   "1991-12", "Roope-Setä 148" ],
    [   "1992-1", "Roope-Setä 149" ],
    [   "1992-2", "Roope-Setä 150" ],
    [   "1992-3", "Roope-Setä 151" ],
    [   "1992-4", "Roope-Setä 152" ],
    [   "1992-5", "Roope-Setä 153" ],
    [   "1992-6", "Roope-Setä 154" ],
    [   "1992-7", "Roope-Setä 155" ],
    [   "1992-8", "Roope-Setä 156" ],
    [   "1992-9", "Roope-Setä 157" ],
    [   "1992-10", "Roope-Setä 158" ],
    [   "1992-11", "Roope-Setä 159" ],
    [   "1992-12", "Roope-Setä 160" ],
    [   "1993-1", "Roope-Setä 161" ],
    [   "1993-2", "Roope-Setä 162" ],
    [   "1993-3", "Roope-Setä 163" ],
    [   "1993-4", "Roope-Setä 164" ],
    [   "1993-5", "Roope-Setä 165" ],
    [   "1993-6", "Roope-Setä 166" ],
    [   "1993-7", "Roope-Setä 167" ],
    [   "1993-8", "Roope-Setä 168" ],
    [   "1993-9", "Roope-Setä 169" ],
    [   "1993-10", "Roope-Setä 170" ],
    [   "1993-11", "Roope-Setä 171" ],
    [   "1993-12", "Roope-Setä 172" ],
    [   "1994-1", "Roope-Setä 173" ],
    [   "1994-2", "Roope-Setä 174" ],
    [   "1994-3", "Roope-Setä 175" ],
    [   "1994-4", "Roope-Setä 176" ],
    [   "1994-5", "Roope-Setä 177" ],
    [   "1994-6", "Roope-Setä 178" ],
    [   "1994-7", "Roope-Setä 179" ],
    [   "1994-8", "Roope-Setä 180" ],
    [   "1994-9", "Roope-Setä 181" ],
    [   "1994-10", "Roope-Setä 182" ],
    [   "1994-11", "Roope-Setä 183" ],
    [   "1994-12", "Roope-Setä 184" ],
    [   "1995-1", "Roope-Setä 185" ],
    [   "1995-2", "Roope-Setä 186" ],
    [   "1995-3", "Roope-Setä 187" ],
    [   "1995-4", "Roope-Setä 188" ],
    [   "1995-5", "Roope-Setä 189" ],
    [   "1995-6", "Roope-Setä 190" ],
    [   "1995-7", "Roope-Setä 191" ],
    [   "1995-8", "Roope-Setä 192" ],
    [   "1995-9", "Roope-Setä 193" ],
    [   "1995-10", "Roope-Setä 194" ],
    [   "1995-11", "Roope-Setä 195" ],
    [   "1995-12", "Roope-Setä 196" ],
    [   "1996-1", "Roope-Setä 197" ],
    [   "1996-2", "Roope-Setä 198" ],
    [   "1996-3", "Roope-Setä 199" ],
    [   "1996-4", "Roope-Setä 200" ],
    [   "1996-5", "Roope-Setä 201" ],
    [   "1996-6", "Roope-Setä 202" ],
    [   "1996-7", "Roope-Setä 203" ],
    [   "1996-8", "Roope-Setä 204" ],
    [   "1996-9", "Roope-Setä 205" ],
    [   "1996-10", "Roope-Setä 206" ],
    [   "1996-11", "Roope-Setä 207" ],
    [   "1996-12", "Roope-Setä 208" ],
    [   "1997-1", "Roope-Setä 209" ],
    [   "1997-2", "Roope-Setä 210" ],
    [   "1997-3", "Roope-Setä 211" ],
    [   "1997-4", "Roope-Setä 212" ],
    [   "1997-5", "Roope-Setä 213" ],
    [   "1997-6", "Roope-Setä 214" ],
    [   "1997-7", "Roope-Setä 215" ],
    [   "1997-8", "Roope-Setä 216" ],
    [   "1997-9", "Roope-Setä 217" ],
    [   "1997-10", "Roope-Setä 218" ],
    [   "1997-11", "Roope-Setä 219" ],
    [   "1997-12", "Roope-Setä 220" ],
    [   "1998-1", "Roope-Setä 221" ],
    [   "1998-2", "Roope-Setä 222" ],
    [   "1998-3", "Roope-Setä 223" ],
    [   "1998-4", "Roope-Setä 224" ],
    [   "1998-5", "Roope-Setä 225" ],
    [   "1998-6", "Roope-Setä 226" ],
    [   "1998-7", "Roope-Setä 227" ],
    [   "1998-8", "Roope-Setä 228" ],
    [   "1998-9", "Roope-Setä 229" ],
    [   "1998-10", "Roope-Setä 230" ],
    [   "1998-11", "Roope-Setä 231" ],
    [   "1998-12", "Roope-Setä 232" ],
    [   "1999-1", "Roope-Setä 233" ],
    [   "1999-2", "Roope-Setä 234" ],
    [   "1999-3", "Roope-Setä 235" ],
    [   "1999-4", "Roope-Setä 236" ],
    [   "1999-5", "Roope-Setä 237" ],
    [   "1999-6", "Roope-Setä 238" ],
    [   "1999-7", "Roope-Setä 239" ],
    [   "1999-8", "Roope-Setä 240" ],
    [   "1999-9", "Roope-Setä 241" ],
    [   "1999-10", "Roope-Setä 242" ],
    [   "1999-11", "Roope-Setä 243" ],
    [   "1999-12", "Roope-Setä 244" ],
    [   "2000-1", "Roope-Setä 245" ],
    [   "2000-2", "Roope-Setä 246" ],
    [   "2000-3", "Roope-Setä 247" ],
    [   "2000-4", "Roope-Setä 248" ],
    [   "2000-5", "Roope-Setä 249" ],
    [   "2000-6", "Roope-Setä 250" ],
    [   "2000-7", "Roope-Setä 251" ],
    [   "2000-8", "Roope-Setä 252" ],
    [   "2000-9", "Roope-Setä 253" ],
    [   "2000-10", "Roope-Setä 254" ],
    [   "2000-11", "Roope-Setä 255" ],
    [   "2000-12", "Roope-Setä 256" ],
    [   "2001-1", "Roope-Setä 257" ],
    [   "2001-2", "Roope-Setä 258" ],
    [   "2001-3", "Roope-Setä 259" ],
    [   "2001-4", "Roope-Setä 260" ],
    [   "2001-5", "Roope-Setä 261" ],
    [   "2001-6", "Roope-Setä 262" ],
    [   "2001-7", "Roope-Setä 263" ],
    [   "2001-8", "Roope-Setä 264" ],
    [   "2001-9", "Roope-Setä 265" ],
    [   "2001-10", "Roope-Setä 266" ],
    [   "2001-11", "Roope-Setä 267" ],
    [   "2001-12", "Roope-Setä 268" ],
    [   "2002-1", "Roope-Setä 269" ],
    [   "2002-2", "Roope-Setä 270" ],
    [   "2002-3", "Roope-Setä 271" ],
    [   "2002-4", "Roope-Setä 272" ],
    [   "2002-5", "Roope-Setä 273" ],
    [   "2002-6", "Roope-Setä 274" ],
    [   "2002-7", "Roope-Setä 275" ],
    [   "2002-8", "Roope-Setä 276" ],
    [   "2002-9", "Roope-Setä 277" ],
    [   "2002-10", "Roope-Setä 278" ],
    [   "2002-11", "Roope-Setä 279" ],
    [   "2002-12", "Roope-Setä 280" ],
    [   "2003-1", "Roope-Setä 281" ],
    [   "2003-2", "Roope-Setä 282" ],
    [   "2003-3", "Roope-Setä 283" ],
    [   "2003-4", "Roope-Setä 284" ],
    [   "2003-5", "Roope-Setä 285" ],
    [   "2003-6", "Roope-Setä 286" ],
    [   "2003-7", "Roope-Setä 287" ],
    [   "2003-8", "Roope-Setä 288" ],
    [   "2003-9", "Roope-Setä 289" ],
    [   "2003-10", "Roope-Setä 290" ],
    [   "2003-11", "Roope-Setä 291" ],
    [   "2003-12", "Roope-Setä 292" ],
    [   "2004-1", "Roope-Setä 293" ],
    [   "2004-2", "Roope-Setä 294" ],
    [   "2004-3", "Roope-Setä 295" ],
    [   "2004-4", "Roope-Setä 296" ],
    [   "2004-5", "Roope-Setä 297" ],
    [   "2004-6", "Roope-Setä 298" ],
    [   "2004-7", "Roope-Setä 299" ],
    [   "2004-8", "Roope-Setä 300" ],
    [   "2004-9", "Roope-Setä 301" ],
    [   "2004-10", "Roope-Setä 302" ],
    [   "2004-11", "Roope-Setä 303" ],
    [   "2004-12", "Roope-Setä 304" ],
    [   "2005-1", "Roope-Setä 305" ],
    [   "2005-2", "Roope-Setä 306" ],
    [   "2005-3", "Roope-Setä 307" ],
    [   "2005-4", "Roope-Setä 308" ],
    [   "2005-5", "Roope-Setä 309" ],
    [   "2005-6", "Roope-Setä 310" ],
    [   "2005-7", "Roope-Setä 311" ],
    [   "2005-8", "Roope-Setä 312" ],
    [   "2005-9", "Roope-Setä 313" ],
    [   "2005-10", "Roope-Setä 314" ],
    [   "2005-11", "Roope-Setä 315" ],
    [   "2005-12", "Roope-Setä 316" ],
    [   "2006-1", "Roope-Setä 317" ],
    [   "2006-2", "Roope-Setä 318" ],
    [   "2006-3", "Roope-Setä 319" ],
    [   "2006-4", "Roope-Setä 320" ],
    [   "2006-5", "Roope-Setä 321" ],
    [   "2006-6", "Roope-Setä 322" ],
    [   "2006-7", "Roope-Setä 323" ],
    [   "2006-8", "Roope-Setä 324" ],
    [   "2006-9", "Roope-Setä 325" ],
    [   "2006-10", "Roope-Setä 326" ],
    [   "2006-11", "Roope-Setä 327" ],
    [   "2006-12", "Roope-Setä 328" ],
    [   "2007-1", "Roope-Setä 329" ],
    [   "2007-2", "Roope-Setä 330" ],
    [   "2007-3", "Roope-Setä 331" ],
    [   "2007-4", "Roope-Setä 332" ],
    [   "2007-5", "Roope-Setä 333" ],
    [   "2007-6", "Roope-Setä 334" ],
    [   "2007-7", "Roope-Setä 335" ],
    [   "2007-8", "Roope-Setä 336" ],
    [   "2007-9", "Roope-Setä 337" ],
    [   "2007-10", "Roope-Setä 338" ],
    [   "2007-11", "Roope-Setä 339" ],
    [   "2007-12", "Roope-Setä 340" ],
    [   "2008-1", "Roope-Setä 341" ],
    [   "2008-2", "Roope-Setä 342" ],
    [   "2008-3", "Roope-Setä 343" ],
    [   "2008-4", "Roope-Setä 344" ],
    [   "2008-5", "Roope-Setä 345" ],
    [   "2008-6", "Roope-Setä 346" ],
    [   "2008-7", "Roope-Setä 347" ],
    [   "2008-8", "Roope-Setä 348" ],
    [   "2008-9", "Roope-Setä 349" ],
    [   "2008-10", "Roope-Setä 350" ],
    [   "2008-11", "Roope-Setä 351" ],
    [   "2008-12", "Roope-Setä 352" ],
    [   "2009-1", "Roope-Setä 353" ],
    [   "2009-2", "Roope-Setä 354" ],
    [   "2009-3", "Roope-Setä 355" ],
    [   "2009-4", "Roope-Setä 356" ],
    [   "2009-5", "Roope-Setä 357" ],
    [   "2009-6", "Roope-Setä 358" ],
    [   "2009-7", "Roope-Setä 359" ],
    [   "2009-8", "Roope-Setä 360" ],
    [   "2009-9", "Roope-Setä 361" ],
    [   "2009-10", "Roope-Setä 362" ],
    [   "2009-11", "Roope-Setä 363" ],
    [   "2009-12", "Roope-Setä 364" ],
    [   "2010-1", "Roope-Setä 365" ],
    [   "2010-2", "Roope-Setä 366" ],
    [   "2010-3", "Roope-Setä 367" ],
    [   "2010-4", "Roope-Setä 368" ],
    [   "2010-5", "Roope-Setä 369" ],
    [   "2010-6", "Roope-Setä 370" ],
    [   "2010-7", "Roope-Setä 371" ],
    [   "2010-8", "Roope-Setä 372" ],
    [   "2010-9", "Roope-Setä 373" ],
    [   "2010-10", "Roope-Setä 374" ],
    [   "2010-11", "Roope-Setä 375" ],
    [   "2010-12", "Roope-Setä 376" ],
    [   "2011-1", "Roope-Setä 377" ],
    [   "2011-2", "Roope-Setä 378" ],
    [   "2011-3", "Roope-Setä 379" ],
    [   "2011-4", "Roope-Setä 380" ],
    [   "2011-5", "Roope-Setä 381" ],
    [   "2011-6", "Roope-Setä 382" ],
    [   "2011-7", "Roope-Setä 383" ],
    [   "2011-8", "Roope-Setä 384" ],
    [   "2011-9", "Roope-Setä 385" ],
    [   "2011-10", "Roope-Setä 386" ],
    [   "2011-11", "Roope-Setä 387" ],
    [   "2011-12", "Roope-Setä 388" ],
    [   "2012-1", "Roope-Setä 389" ],
    [   "2012-2", "Roope-Setä 390" ],
    [   "2012-3", "Roope-Setä 391" ],
    [   "2012-4", "Roope-Setä 392" ],
    [   "2012-5", "Roope-Setä 393" ],
    [   "2012-6", "Roope-Setä 394" ],
    [   "2012-7", "Roope-Setä 395" ],
    [   "2012-8", "Roope-Setä 396" ],
    [   "2012-9", "Roope-Setä 397" ],
    [   "2012-10", "Roope-Setä 398" ],
    [   "2012-11", "Roope-Setä 399" ],
    [   "2012-12", "Roope-Setä 400" ],
    [   "2013-1", "Roope-Setä 401" ],
    [   "2013-2", "Roope-Setä 402" ],
    [   "2013-3", "Roope-Setä 403" ],
    [   "2013-4", "Roope-Setä 404" ],
    [   "2013-5", "Roope-Setä 405" ],
    [   "2013-6", "Roope-Setä 406" ],
    [   "2013-7", "Roope-Setä 407" ],
    [   "2013-8", "Roope-Setä 408" ],
    [   "2013-9", "Roope-Setä 409" ],
    [   "2013-10", "Roope-Setä 410" ],
    [   "2013-11", "Roope-Setä 411" ],
    [   "2013-12", "Roope-Setä 412" ],
    [   "2014-1", "Roope-Setä 413" ],
    [   "2014-2", "Roope-Setä 414" ],
    [   "2014-3", "Roope-Setä 415" ],
    [   "2014-4", "Roope-Setä 416" ],
    [   "2014-5", "Roope-Setä 417" ],
    [   "2014-6", "Roope-Setä 418" ],
    [   "2014-7", "Roope-Setä 419" ],
    [   "2014-8", "Roope-Setä 420" ],
    [   "2014-9", "Roope-Setä 421" ],
    [   "2014-10", "Roope-Setä 422" ],
    [   "2014-11", "Roope-Setä 423" ],
    [   "2014-12", "Roope-Setä 424" ],
    [   "2015-1", "Roope-Setä 425 - Platina: Romano Scarpa" ],
    [   "2015-2", "Roope-Setä 426" ],
    [   "2015-3", "Roope-Setä 427" ],
    [   "2015-4", "Roope-Setä 428 - Platina: Giorgio Cavazzano" ],
    [   "2015-5", "Roope-Setä 429" ],
    [   "2015-6", "Roope-Setä 430 - Platina: Silvia Ziche" ],
    [   "2015-7", "Roope-Setä 431" ],
    [   "2015-8", "Roope-Setä 432" ],
    [   "2015-9", "Roope-Setä 433 - Platina: Luciano Bottaro" ],
    [   "2015-10", "Roope-Setä 434" ],
    [   "2016-1", "Roope-Setä 435 - Platina: Corrado Mastantuono" ],
    [   "2016-2", "Roope-Setä 436" ],
    [   "2016-3", "Roope-Setä 437" ],
    [   "2016-4", "Roope-Setä 438 - Platina: Giovan Battista Carpi" ],
    [   "2016-5", "Roope-Setä 439" ],
    [   "2016-6", "Roope-Setä 440 - Platina: Casty" ],
    [   "2016-7", "Roope-Setä 441" ],
    [   "2016-8", "Roope-Setä 442" ],
    [   "2016-9", "Roope-Setä 443 - Platina: Romano Scarpa" ],
    [   "2016-10", "Roope-Setä 444" ],
    [   "2017-1", "Roope-Setä 445 - Platina: Marco Rota" ],
    [   "2017-2", "Roope-Setä 446" ],
    [   "2017-3", "Roope-Setä 447" ],
    [   "2017-4", "Roope-Setä 448 - Platina: Massimo De Vita" ],
    [   "2017-5", "Roope-Setä 449" ],
    [   "2017-6", "Roope-Setä 450 - Platina: Enrico Faccini" ],
    [   "2017-7", "Roope-Setä 451" ],
    [   "2017-8", "Roope-Setä 452" ],
    [   "2017-9", "Roope-Setä 453 - Platina: Giorgio Cavazzano"],
    [   "2017-10", "Roope-Setä 454 - Lajinsa viimeinen!"]
]

